name: Auto Commit e Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e Push se houver mudanças
        run: |
          git add .
          git commit -m "Atualização automática pelo GitHub Actions" || echo "Nenhuma mudança para commit"
          git push
