name: Auto Commit and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

job:
  auto-commit:
    runs-on:
      ubuntu-latest

  steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git add .
        git commit -m "Atualização automática" || echo "Nenhuma mudança"
        git push
